/* @/lib/constants/core/product-categories.ts */

export const PRODUCT_CATEGORIES = {
  "digital_course": "Digital Course",
  "digital_download": "Digital Download",
  "digital_membership": "Digital Membership",
  "digital_subscription": "Digital Subscription",
  "digital_bundle": "Digital Bundle",
  "physical_product": "Physical Product",
  "physical_handmade": "Physical Handmade",
  "physical_manufactured": "Physical Manufactured",
  "physical_custom": "Physical Custom",
  "audio": "Audio",
  "video": "Video",
  "podcast": "Podcast",
  "music": "Music",
  "livestream": "Livestream",
  "event_live": "Event Live",
  "event_virtual": "Event Virtual",
  "workshop": "Workshop",
  "class": "Class",
  "consultation": "Consultation",
  "service": "Service",
  "commission": "Commission",
  "contract": "Contract",
  "sponsorship": "Sponsorship",
  "mutual_aid": "Mutual Aid",
  "crowdfunding": "Crowdfunding",
  "tip": "Tip",
  "donation": "Donation",
  "clothing": "Clothing",
  "accessory": "Accessory",
  "fabric": "Fabric",
  "pattern": "Pattern",
  "bundle": "Bundle",
  "kit": "Kit",
  "subscription_box": "Subscription Box"
} as const;

export type PrductCategories = typeof PRODUCT_CATEGORIES[keyof typeof PRODUCT_CATEGORIES];