// src/scripts/setup-enum-mapping.ts
// Run once to generate the enum mapping config from first reference analysis

import { readDatabaseTypes } from './shared/fileReader.js';
import { findMarkers } from './modules/findMarkers.js';
import { findAllClosingBraces } from './modules/findClosingBraces.js';
import { countAllCollections } from './modules/countItems.js';
import { extractObject } from './modules/extractObject.js';
import { getDeityGroupForTable, getFolderNameForTable } from '../config/deity-groups.js';
import { 
  logHeader, logSuccess, logError, logInfo, 
  logSeparator, logWarning, logDebug 
} from './shared/logger.js';
import * as fs from 'fs';
import * as path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const PROJECT_ROOT = path.resolve(__dirname, '../..');
const OUTPUT_PATH = path.join(PROJECT_ROOT, 'src/config/enum-mapping.ts');

async function main(): Promise<void> {
  console.log('\n');
  logSeparator();
  logHeader('🏛️ ENUM MAPPING SETUP');
  logSeparator();
  console.log('\n');
  
  // Read and parse the database types file
  const fileResult = readDatabaseTypes();
  if (!fileResult.success) {
    logError(`Failed to read file: ${fileResult.error}`);
    process.exit(1);
  }
  
  const lines = fileResult.content.split(/\r?\n/);
  logSuccess(`File loaded: ${lines.length} lines`);
  
  // Find markers
  const markers = findMarkers(lines, { verbose: false });
  const completeMarkers = findAllClosingBraces(lines, markers, { verbose: false });
  const collections = countAllCollections(lines, completeMarkers, { verbose: false });
  
  logInfo(`Processing ${collections.tables.itemCount} tables to find enum references...`);
  
  // Build mapping: enumName -> { folderName, firstTable }
  const enumMapping = new Map<string, { folderName: string; referencedIn: string }>();
  
  // Process tables in deity group order (so first reference respects priority)
  // Get all tables with their deity groups
  const tablesWithGroups: { name: string; folderName: string }[] = [];
  
  for (const tableName of collections.tables.itemNames) {
    const deityGroup = getDeityGroupForTable(tableName);
    const folderName = deityGroup?.folderName || 'hestia_core';
    tablesWithGroups.push({ name: tableName, folderName });
  }
  
  // Sort by deity group sequence (optional, for predictable first reference)
  // Process in order of deity groups as defined
  for (const { name: tableName, folderName } of tablesWithGroups) {
    // Extract table content
    const tableContent = extractObject(
      lines,
      completeMarkers.tablesLine,
      completeMarkers.tablesEndLine,
      tableName,
      { verbose: false }
    );
    
    if (tableContent) {
      // Find enum references in the table content
      const enumPattern = /Database\["public"\]\["Enums"\]\["(\w+)"\]/g;
      let match;
      while ((match = enumPattern.exec(tableContent.content)) !== null) {
        const enumName = match[1];
        // Only record the FIRST reference (skip if already mapped)
        if (!enumMapping.has(enumName)) {
          enumMapping.set(enumName, {
            folderName: folderName,
            referencedIn: tableName
          });
          logDebug(`  ${enumName} → ${folderName} (from ${tableName})`);
        }
      }
    }
  }
  
  logSuccess(`Mapped ${enumMapping.size} enums to deity folders`);
  
  // Find unmapped runtime enums
  // Parse runtime enums from Constants.public.Enums
  let runtimeEnumNames: string[] = [];
  if (completeMarkers.constantsEnumsLine !== -1 && completeMarkers.constantsEnumsEndLine !== -1) {
    const constantsEnumsStartIdx = completeMarkers.constantsEnumsLine - 1;
    const constantsEnumsEndIdx = completeMarkers.constantsEnumsEndLine - 1;
    const constantsEnumsLines = lines.slice(constantsEnumsStartIdx, constantsEnumsEndIdx + 1);
    const constantsEnumsContent = constantsEnumsLines.join('\n');
    
    const regex = /^\s{6}(\w+):\s*\[([\s\S]*?)\],/gm;
    let match;
    while ((match = regex.exec(constantsEnumsContent)) !== null) {
      runtimeEnumNames.push(match[1]);
    }
  }
  
  // Find unmapped enums (in runtime but not mapped from tables)
  const unmappedEnums = runtimeEnumNames.filter(name => !enumMapping.has(name));
  if (unmappedEnums.length > 0) {
    logWarning(`${unmappedEnums.length} enums have no table reference:`);
    for (const enumName of unmappedEnums.slice(0, 20)) {
      logDebug(`    ${enumName}`);
    }
    if (unmappedEnums.length > 20) {
      logDebug(`    ... and ${unmappedEnums.length - 20} more`);
    }
    logInfo('These will use default folder "hestia_core"');
  }
  
  // Generate the enum-mapping.ts file
  const timestamp = new Date().toISOString();
  let fileContent = `// src/config/enum-mapping.ts\n`;
  fileContent += `// AUTO-GENERATED by setup-enum-mapping.ts\n`;
  fileContent += `// Generated: ${timestamp}\n`;
  fileContent += `// Maps each enum to the deity folder of the first table that references it\n\n`;
  
  fileContent += `export interface EnumMapping {\n`;
  fileContent += `  enumName: string;\n`;
  fileContent += `  folderName: string;\n`;
  fileContent += `  referencedIn: string;\n`;
  fileContent += `}\n\n`;
  
  fileContent += `export const ENUM_FOLDER_MAPPING: Record<string, string> = {\n`;
  
  // Sort by folder name then enum name
  const sortedEntries = Array.from(enumMapping.entries())
    .sort((a, b) => {
      if (a[1].folderName !== b[1].folderName) {
        return a[1].folderName.localeCompare(b[1].folderName);
      }
      return a[0].localeCompare(b[0]);
    });
  
  for (const [enumName, { folderName, referencedIn }] of sortedEntries) {
    fileContent += `  "${enumName}": "${folderName}", // from ${referencedIn}\n`;
  }
  
  fileContent += `\n  // Default fallback\n`;
  fileContent += `  "default": "hestia_core"\n`;
  fileContent += `};\n\n`;
  
  fileContent += `export function getEnumFolder(enumName: string): string {\n`;
  fileContent += `  return ENUM_FOLDER_MAPPING[enumName] || ENUM_FOLDER_MAPPING.default;\n`;
  fileContent += `}\n`;
  
  // Write the file
  fs.writeFileSync(OUTPUT_PATH, fileContent, 'utf-8');
  logSuccess(`Generated: ${OUTPUT_PATH}`);
  
  // Print summary
  console.log('\n');
  logSeparator();
  logInfo('ENUM MAPPING SUMMARY');
  logSeparator();
  console.log('');
  
  // Group by folder
  const byFolder: Record<string, string[]> = {};
  for (const [enumName, { folderName }] of enumMapping) {
    if (!byFolder[folderName]) byFolder[folderName] = [];
    byFolder[folderName].push(enumName);
  }
  
  for (const [folder, enums] of Object.entries(byFolder).sort()) {
    logInfo(`  ${folder}: ${enums.length} enums`);
    for (const enumName of enums.slice(0, 5)) {
      console.log(`      └─ ${enumName}`);
    }
    if (enums.length > 5) {
      console.log(`      └─ ... and ${enums.length - 5} more`);
    }
    console.log('');
  }
  
  logSuccess('Setup complete. You can now use getEnumFolder() for enum folder mapping.');
}

main().catch((error) => {
  logError(`Fatal error: ${error.message}`);
  process.exit(1);
});