export const Constants = {
  graphql_public: {
    Enums: {},
  },
  public: {
    Enums: {
      acid_persona: [
        "masked_traveler",
        "tab_hoarder",
        "seam_warrior",
        "void_dweller",
        "pattern_seeker",
        "quantum_witness",
      ],
      acid_question_type: [
        "multiple_choice",
        "slider",
        "checkbox",
        "scale",
        "text",
      ],
      action_type: [
        "post",
        "comment",
        "reaction",
        "emerald",
        "follow",
        "subscribe",
        "purchase",
        "join_house",
        "complete_quest",
        "earn_badge",
      ],
      activity_visibility: ["public", "followers", "private"],
      admin_log_category: [
        "user_management",
        "content_moderation",
        "financial",
        "system_config",
        "verification",
        "report_handling",
      ],
      admin_log_target_type: [
        "user",
        "creator",
        "vendor",
        "product",
        "sale",
        "payout",
        "report",
        "system",
      ],
      analytics_category: [
        "page_view",
        "user_action",
        "system",
        "error",
        "performance",
      ],
      application_status: [
        "pending",
        "reviewing",
        "approved",
        "rejected",
        "needs_info",
      ],
      application_type: ["creator", "vendor", "mentor", "moderator"],
      badge_rarity: ["common", "rare", "epic", "legendary", "mythic"],
      badge_tier: ["initiate", "adept", "master"],
      badge_type: [
        "quantum_weaver",
        "founding_council",
        "genesis_block",
        "sanctuary_guardian",
        "verified_creator",
        "verified_vendor",
        "community_leader",
        "first_sale",
        "first_purchase",
        "first_quest",
        "quest_master",
        "sovereign_seeker",
        "sovereign_adept",
        "sovereign_master",
        "contributor_concept",
        "contributor_code",
        "contributor_design",
        "contributor_content",
        "contributor_testing",
        "hearth_keeper_initiate",
        "hearth_keeper_adept",
        "hearth_keeper_master",
        "chancellor_initiate",
        "chancellor_adept",
        "chancellor_master",
        "seer_initiate",
        "seer_adept",
        "seer_master",
        "aethelred_initiate",
        "aethelred_adept",
        "aethelred_master",
        "curator_initiate",
        "curator_adept",
        "curator_master",
        "archivist_initiate",
        "archivist_adept",
        "archivist_master",
        "skald_initiate",
        "skald_adept",
        "skald_master",
        "codex_initiate",
        "codex_adept",
        "codex_master",
        "executioner_initiate",
        "executioner_adept",
        "executioner_master",
        "bigot_tax_exempt",
        "data_sovereign",
        "privacy_pioneer",
      ],
      bid_type: ["cpm", "cpc", "cpa"],
      bridge_status: ["active", "dormant", "transforming"],
      business_type: [
        "sole_proprietor",
        "llc",
        "nonprofit",
        "cooperative",
        "partnership",
        "other",
      ],
      calendar_event_type: [
        "holiday",
        "ritual",
        "milestone",
        "maintenance",
        "release",
      ],
      calendar_visibility: ["public", "house", "admin"],
      campaign_status: ["draft", "active", "paused", "completed"],
      communication_style: ["direct", "gentle", "detailed", "concise"],
      contact_direction: ["inbound", "outbound"],
      contact_status: ["new", "read", "replied", "resolved", "spam"],
      content_rating: ["general", "mature", "triggering", "explicit"],
      content_type: ["text", "image", "audio", "video", "mixed"],
      contribution_type: [
        "concept",
        "code",
        "design",
        "content",
        "testing",
        "promotion",
        "infrastructure",
      ],
      council_house: [
        "hearth_keeper",
        "chancellor",
        "seer",
        "aethelred",
        "curator",
        "archivist",
        "skald",
        "codex",
        "executioner",
      ],
      currency_position_type: ["before", "after"],
      custom_category_type: [
        "greeting",
        "communication",
        "gift",
        "taboo",
        "celebration",
        "business",
        "family",
      ],
      date_format_type: ["YYYY-MM-DD", "MM/DD/YYYY", "DD/MM/YYYY"],
      delivery_status: ["operational", "degraded", "failed"],
      deployment_status: ["success", "building", "failed"],
      difficulty_level: ["beginner", "intermediate", "advanced", "master"],
      email_status: [
        "queued",
        "sent",
        "delivered",
        "opened",
        "clicked",
        "bounced",
        "failed",
      ],
      emerald_status: ["active", "refunded", "failed"],
      escalation_target: ["admin", "council", "executioner"],
      folksonomy_target_type: [
        "post",
        "product",
        "comment",
        "profile",
        "quest",
        "myth",
        "lesson",
        "scene",
      ],
      job_status: ["active", "paused", "completed", "failed"],
      job_type: ["cron", "one_time", "interval"],
      ledger_entity: ["buyer", "platform", "creator", "contributor"],
      ledger_entry_type: ["sale", "residual", "platform_fee", "payout"],
      lesson_content_type: [
        "text",
        "video",
        "audio",
        "interactive",
        "quiz",
        "exercise",
      ],
      life_cycle_phase: [
        "seedling",
        "sprout",
        "bloom",
        "harvest",
        "dormant",
        "renewal",
      ],
      maintenance_status: [
        "scheduled",
        "in_progress",
        "completed",
        "failed",
        "cancelled",
      ],
      maintenance_type: ["upgrade", "backup", "repair", "cleanup", "migration"],
      measurement_system_type: ["metric", "imperial", "us_customary"],
      message_status: ["sent", "delivered", "read", "deleted"],
      moderation_action_type: [
        "hide",
        "unhide",
        "delete",
        "restore",
        "warn",
        "suspend",
        "ban",
        "mute",
        "unmute",
        "verify",
        "unverify",
        "feature",
        "unfeature",
      ],
      moderation_target_type: [
        "user",
        "post",
        "comment",
        "reply",
        "product",
        "message",
        "channel",
      ],
      myth_type: ["origin", "parable", "ritual", "prophecy", "chronicle"],
      notification_type: [
        "comment_reply",
        "emerald_received",
        "subscription_renewal",
        "product_purchased",
        "application_approved",
        "application_rejected",
        "report_resolved",
        "report_rejected",
        "system_announcement",
        "quest_completed",
        "badge_earned",
        "house_promotion",
        "mentor_assigned",
      ],
      ontology_predicate: [
        "parent_of",
        "related_to",
        "requires",
        "contradicts",
        "evolves_to",
        "inspired_by",
      ],
      owner_type: ["creator", "vendor"],
      payment_status: ["pending", "completed", "refunded", "failed"],
      payout_frequency: ["weekly", "monthly", "quarterly"],
      payout_method: ["stripe", "paypal", "bank", "crypto"],
      payout_status: ["pending", "processing", "completed", "failed"],
      platform_environment: ["development", "staging", "production"],
      platform_status: ["operational", "degraded", "outage", "maintenance"],
      post_visibility: [
        "public",
        "subscribers",
        "tier_community",
        "tier_ally",
        "tier_corporate",
        "private",
      ],
      process_type: [
        "appeal",
        "verification",
        "payout_dispute",
        "content_review",
        "role_application",
      ],
      product_type: [
        "digital_course",
        "digital_download",
        "digital_membership",
        "digital_subscription",
        "digital_bundle",
        "physical_product",
        "physical_handmade",
        "physical_manufactured",
        "physical_custom",
        "audio",
        "video",
        "podcast",
        "music",
        "livestream",
        "event_live",
        "event_virtual",
        "workshop",
        "class",
        "consultation",
        "service",
        "commission",
        "contract",
        "sponsorship",
        "mutual_aid",
        "crowdfunding",
        "tip",
        "donation",
        "clothing",
        "accessory",
        "fabric",
        "pattern",
        "bundle",
        "kit",
        "subscription_box",
      ],
      progress_status: ["not_started", "in_progress", "completed", "mastered"],
      protocol_type: [
        "security",
        "incident",
        "escalation",
        "onboarding",
        "offboarding",
        "emergency",
      ],
      quest_status: [
        "locked",
        "available",
        "in_progress",
        "completed",
        "mastered",
      ],
      reaction_type: [
        "resonate",
        "support",
        "appreciate",
        "empathy",
        "celebrate",
      ],
      recurring_interval: ["month", "year"],
      report_status: [
        "pending",
        "reviewing",
        "resolved",
        "dismissed",
        "escalated",
      ],
      report_target_type: [
        "post",
        "comment",
        "reply",
        "product",
        "message",
        "profile",
        "channel",
      ],
      report_type: [
        "inappropriate_content",
        "harassment",
        "spam",
        "hate_speech",
        "impersonation",
        "copyright",
        "other",
      ],
      scene_type: [
        "ritual",
        "ceremony",
        "celebration",
        "initiation",
        "council",
        "vision_quest",
      ],
      script_type: ["deploy", "seed", "migration", "cleanup", "backup", "test"],
      setting_scope: ["global", "user", "role", "house"],
      source_pool_type: ["residual", "covenant", "platform"],
      stripe_mode: ["test", "live"],
      submission_type: [
        "text",
        "image",
        "file",
        "audio",
        "video",
        "link",
        "auto",
      ],
      subscription_status: ["active", "paused", "cancelled", "expired"],
      supabase_status: ["connected", "degraded", "disconnected"],
      superposition_status: ["active", "collapsed", "archived"],
      survey_audience_type: [
        "all",
        "creators",
        "vendors",
        "subscribers",
        "council",
      ],
      system_status: ["operational", "degraded", "outage", "maintenance"],
      system_type: ["database", "api", "storage", "auth", "queue", "cache"],
      target_type: [
        "post",
        "comment",
        "product",
        "user",
        "channel",
        "quest",
        "badge",
      ],
      taxonomy_node_type: [
        "domain",
        "category",
        "concept",
        "relationship",
        "attribute",
      ],
      text_direction_type: ["ltr", "rtl"],
      time_format_type: ["12h", "24h"],
      timeline_event_type: [
        "quest_completed",
        "badge_earned",
        "path_completed",
        "milestone_reached",
        "house_joined",
        "ritual_performed",
        "scene_witnessed",
      ],
      transaction_type: [
        "sale",
        "residual",
        "disbursement",
        "payout",
        "refund",
      ],
      translatable_type: ["post", "product", "quest", "myth", "lesson", "page"],
      user_status: ["active", "suspended", "deleted"],
      user_tier: ["community", "ally", "corporate", "council"],
      verification_status: ["pending", "verified", "rejected", "suspended"],
      webhook_status: ["active", "failed", "disabled"],
      workflow_status: ["passing", "failing", "pending"],
    },
  },
} as const
