// ============================================================================
// DEPENDENCY MAP - MAINTAINED by COSMIC and GAIA
// ============================================================================
// "⚠️⚠️⚠️" src/config/dependency-map.ts           "⚠️⚠️⚠️"
// "⚠️⚠️⚠️" AUTOGENERATED - DO NOT EDIT MANUALLY   "⚠️⚠️⚠️"
// "⚠️⚠️⚠️" Updated by COSMIC and GAIA on each run "⚠️⚠️⚠️"
// Purpose: Track dependencies between all system files
// ============================================================================

export interface DependencyNode {
  id: string;                    // file path or module name
  type: 'source' | 'generated' | 'config' | 'external';
  exports: string[];             // what this file exports
  imports: string[];             // what this file imports
  usedBy: string[];              // what files use this
  fileHash?: string;             // for change detection
  lastModified?: string;         // timestamp of last change
}

export interface DependencyEdge {
  from: string;
  to: string;
  type: 'imports' | 'extends' | 'references' | 'generates';
}

export interface DependencyMap {
  version: string;
  lastAnalyzed: string;
  nodes: Record<string, DependencyNode>;
  edges: DependencyEdge[];
}

// ============================================================================
// DEFAULT DEPENDENCY MAP
// ============================================================================

export const DEPENDENCY_MAP: DependencyMap = {
  version: '1.0.0',
  lastAnalyzed: new Date().toISOString(),
  nodes: {},
  edges: []
};

// ============================================================================
// HELPER FUNCTIONS
// ============================================================================

/**
 * Save the dependency map to disk
 */
export function saveDependencyMap(map: DependencyMap): void {
  // TODO: Write to config/dependency-map.ts
}

/**
 * Load the dependency map from disk
 */
export function loadDependencyMap(): DependencyMap {
  // TODO: Read file if exists, else return default
}

/**
 * Add or update a node in the map
 */
export function upsertNode(map: DependencyMap, node: DependencyNode): DependencyMap {
  // TODO: Add or update node, preserve existing relationships
}

/**
 * Add an edge between nodes
 */
export function addEdge(map: DependencyMap, edge: DependencyEdge): DependencyMap {
  // TODO: Add edge if not exists
}

/**
 * Find all nodes affected by a change to a specific node
 * Returns nodes in dependency order (dependents first)
 */
export function findAffectedNodes(map: DependencyMap, nodeId: string): string[] {
  // TODO: Traverse dependency chain from nodeId
  // TODO: Return array of affected node IDs in order
}

/**
 * Detect changes between two dependency maps
 */
export function detectChanges(oldMap: DependencyMap, newMap: DependencyMap): {
  added: string[];
  removed: string[];
  modified: string[];
} {
  // TODO: Compare nodes and return changes
}