// src/config/dependency_map.ts
// ============================================================================
// DEPENDENCY MAP - MAINTAINED by COSMIC and GAIA
// ============================================================================
// ⚠️⚠️⚠️ AUTOGENERATED - DO NOT EDIT MANUALLY   ⚠️⚠️⚠️
// ⚠️⚠️⚠️ Updated by COSMIC and GAIA on each run ⚠️⚠️⚠️
// Purpose: Track dependencies between all system files
// ============================================================================

import * as fs from 'fs';
import * as path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const PROJECT_ROOT = path.resolve(__dirname, '../..');
const MAP_PATH = path.join(PROJECT_ROOT, 'src/config/dependency_map.ts');

export interface DependencyNode {
  id: string;
  type: 'source' | 'generated' | 'config' | 'external';
  exports: string[];
  imports: string[];
  usedBy: string[];
  fileHash?: string;
  lastModified?: string;
}

export interface DependencyEdge {
  from: string;
  to: string;
  type: 'imports' | 'extends' | 'references' | 'generates';
}

export interface DependencyMap {
  version: string;
  lastAnalyzed: string;
  nodes: Record<string, DependencyNode>;
  edges: DependencyEdge[];
}

// ============================================================================
// DEFAULT DEPENDENCY MAP
// ============================================================================

let DEPENDENCY_MAP: DependencyMap = {
  version: '1.0.0',
  lastAnalyzed: new Date().toISOString(),
  nodes: {},
  edges: []
};

// Load existing map from file
function loadMap(): void {
  if (!fs.existsSync(MAP_PATH)) return;
  
  try {
    const content = fs.readFileSync(MAP_PATH, 'utf-8');
    const match = content.match(/export const DEPENDENCY_MAP: DependencyMap = ({[\s\S]*?});/);
    if (match) {
      DEPENDENCY_MAP = JSON.parse(match[1]);
    }
  } catch (error) {
    console.warn(`Failed to load dependency map: ${error}`);
  }
}

// Save map to file
function saveMap(): void {
  const content = `// src/config/dependency_map.ts
// ============================================================================
// DEPENDENCY MAP - MAINTAINED by COSMIC and GAIA
// ============================================================================
// ⚠️⚠️⚠️ AUTOGENERATED - DO NOT EDIT MANUALLY   ⚠️⚠️⚠️
// ⚠️⚠️⚠️ Updated by COSMIC and GAIA on each run ⚠️⚠️⚠️
// ============================================================================

export interface DependencyNode {
  id: string;
  type: 'source' | 'generated' | 'config' | 'external';
  exports: string[];
  imports: string[];
  usedBy: string[];
  fileHash?: string;
  lastModified?: string;
}

export interface DependencyEdge {
  from: string;
  to: string;
  type: 'imports' | 'extends' | 'references' | 'generates';
}

export interface DependencyMap {
  version: string;
  lastAnalyzed: string;
  nodes: Record<string, DependencyNode>;
  edges: DependencyEdge[];
}

export const DEPENDENCY_MAP: DependencyMap = ${JSON.stringify(DEPENDENCY_MAP, null, 2)};
`;

  fs.writeFileSync(MAP_PATH, content, 'utf-8');
}

// Load on module initialization
loadMap();

// ============================================================================
// HELPER FUNCTIONS
// ============================================================================

/**
 * Save the dependency map to disk
 */
export function saveDependencyMap(map: DependencyMap): void {
  DEPENDENCY_MAP = map;
  DEPENDENCY_MAP.lastAnalyzed = new Date().toISOString();
  saveMap();
}

/**
 * Load the dependency map from disk
 */
export function loadDependencyMap(): DependencyMap {
  loadMap();
  return DEPENDENCY_MAP;
}

/**
 * Add or update a node in the map
 */
export function upsertNode(map: DependencyMap, node: DependencyNode): DependencyMap {
  const existing = map.nodes[node.id];
  if (existing) {
    // Preserve usedBy relationships from existing node
    node.usedBy = existing.usedBy;
  }
  map.nodes[node.id] = node;
  return map;
}

/**
 * Add an edge between nodes
 */
export function addEdge(map: DependencyMap, edge: DependencyEdge): DependencyMap {
  // Check if edge already exists
  const exists = map.edges.some(e => e.from === edge.from && e.to === edge.to && e.type === edge.type);
  if (!exists) {
    map.edges.push(edge);
    
    // Update usedBy on the target node
    const targetNode = map.nodes[edge.to];
    if (targetNode && !targetNode.usedBy.includes(edge.from)) {
      targetNode.usedBy.push(edge.from);
    }
  }
  return map;
}

/**
 * Find all nodes affected by a change to a specific node
 * Returns nodes in dependency order (dependents first)
 */
export function findAffectedNodes(map: DependencyMap, nodeId: string): string[] {
  const affected: string[] = [];
  const visited = new Set<string>();
  
  function traverse(currentId: string) {
    if (visited.has(currentId)) return;
    visited.add(currentId);
    
    const node = map.nodes[currentId];
    if (node) {
      for (const dependentId of node.usedBy) {
        if (!affected.includes(dependentId)) {
          affected.push(dependentId);
        }
        traverse(dependentId);
      }
    }
  }
  
  traverse(nodeId);
  return affected;
}

/**
 * Detect changes between two dependency maps
 */
export function detectChanges(oldMap: DependencyMap, newMap: DependencyMap): {
  added: string[];
  removed: string[];
  modified: string[];
} {
  const added: string[] = [];
  const removed: string[] = [];
  const modified: string[] = [];
  
  const oldNodes = new Set(Object.keys(oldMap.nodes));
  const newNodes = new Set(Object.keys(newMap.nodes));
  
  // Find added nodes
  for (const node of newNodes) {
    if (!oldNodes.has(node)) {
      added.push(node);
    }
  }
  
  // Find removed nodes
  for (const node of oldNodes) {
    if (!newNodes.has(node)) {
      removed.push(node);
    }
  }
  
  // Find modified nodes (exist in both but changed)
  for (const node of oldNodes) {
    if (newNodes.has(node)) {
      const oldNode = oldMap.nodes[node];
      const newNode = newMap.nodes[node];
      
      if (JSON.stringify(oldNode.exports) !== JSON.stringify(newNode.exports) ||
          JSON.stringify(oldNode.imports) !== JSON.stringify(newNode.imports)) {
        modified.push(node);
      }
    }
  }
  
  return { added, removed, modified };
}

/**
 * Get all nodes that depend on a specific file type
 */
export function getNodesByType(map: DependencyMap, type: DependencyNode['type']): string[] {
  return Object.entries(map.nodes)
    .filter(([_, node]) => node.type === type)
    .map(([id]) => id);
}

/**
 * Get dependency graph as a simplified structure for visualization
 */
export function getDependencyGraph(map: DependencyMap): {
  nodes: { id: string; type: string; size: number }[];
  edges: { source: string; target: string }[];
} {
  const nodes = Object.entries(map.nodes).map(([id, node]) => ({
    id,
    type: node.type,
    size: node.exports.length + node.imports.length
  }));
  
  const edges = map.edges.map(edge => ({
    source: edge.from,
    target: edge.to
  }));
  
  return { nodes, edges };
}