// src/config/efficiency-records.ts
// ============================================================================
// EFFICIENCY RECORDS - Performance tracking for COSMIC and GAIA
// ============================================================================
// ⚠️⚠️⚠️ AUTOGENERATED - DO NOT EDIT MANUALLY   ⚠️⚠️⚠️
// ⚠️⚠️⚠️ Updated by COSMIC and GAIA on each run ⚠️⚠️⚠️
// Purpose: Track generation times, file sizes, and resource usage
// ============================================================================

import * as fs from 'fs';
import * as path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const PROJECT_ROOT = path.resolve(__dirname, '../..');
const RECORDS_PATH = path.join(PROJECT_ROOT, 'src/config/efficiency-records.ts');

export interface ProcessingRecord {
  id: string;
  timestamp: string;
  system: 'COSMIC' | 'GAIA';
  totalFilesGenerated: number;
  totalTimeMs: number;
  averageTimePerFile: number;
  cacheHits: number;
  cacheMisses: number;
  memoryUsage: number;
  fileTypeBreakdown: Record<string, number>;
}

export interface ResourceProfile {
  fileType: string;
  averageGenerationTimeMs: number;
  typicalSize: number;
  dependencies: string[];
}

// ============================================================================
// DEFAULT RECORDS
// ============================================================================

let EFFICIENCY_RECORDS: ProcessingRecord[] = [];
let RESOURCE_PROFILES: ResourceProfile[] = [
  { fileType: 'constants', averageGenerationTimeMs: 5, typicalSize: 500, dependencies: ['enums'] },
  { fileType: 'types', averageGenerationTimeMs: 15, typicalSize: 2000, dependencies: ['tables', 'enums'] },
  { fileType: 'validators', averageGenerationTimeMs: 10, typicalSize: 1500, dependencies: ['types'] },
  { fileType: 'utils', averageGenerationTimeMs: 20, typicalSize: 3000, dependencies: ['types', 'validators'] },
  { fileType: 'api', averageGenerationTimeMs: 25, typicalSize: 2500, dependencies: ['utils', 'validators'] },
  { fileType: 'hooks', averageGenerationTimeMs: 15, typicalSize: 1800, dependencies: ['api', 'types'] },
  { fileType: 'css-variables', averageGenerationTimeMs: 8, typicalSize: 3000, dependencies: ['colors'] },
  { fileType: 'tailwind-config', averageGenerationTimeMs: 12, typicalSize: 5000, dependencies: ['colors', 'motion'] },
  { fileType: 'domain-styles', averageGenerationTimeMs: 10, typicalSize: 4000, dependencies: ['colors'] },
  { fileType: 'text-effects', averageGenerationTimeMs: 8, typicalSize: 3500, dependencies: ['colors', 'motion'] },
  { fileType: 'animation-variants', averageGenerationTimeMs: 10, typicalSize: 4000, dependencies: ['motion', 'consciousness'] },
  { fileType: 'typography', averageGenerationTimeMs: 12, typicalSize: 6000, dependencies: ['typography', 'dimensions'] },
  { fileType: 'zoom-targets', averageGenerationTimeMs: 5, typicalSize: 2000, dependencies: ['positioning'] },
  { fileType: 'parallax', averageGenerationTimeMs: 5, typicalSize: 2500, dependencies: ['positioning'] }
];

// Load existing records from file
function loadRecords(): void {
  if (!fs.existsSync(RECORDS_PATH)) return;
  
  try {
    const content = fs.readFileSync(RECORDS_PATH, 'utf-8');
    const match = content.match(/export const EFFICIENCY_RECORDS: ProcessingRecord\[\] = (\[[\s\S]*?\]);/);
    if (match) {
      EFFICIENCY_RECORDS = JSON.parse(match[1]);
    }
    const profileMatch = content.match(/export const RESOURCE_PROFILES: ResourceProfile\[\] = (\[[\s\S]*?\]);/);
    if (profileMatch) {
      RESOURCE_PROFILES = JSON.parse(profileMatch[1]);
    }
  } catch (error) {
    console.warn(`Failed to load efficiency records: ${error}`);
  }
}

// Save records to file
function saveRecords(): void {
  const content = `// src/config/efficiency-records.ts
// ============================================================================
// EFFICIENCY RECORDS - Performance tracking for COSMIC and GAIA
// ============================================================================
// ⚠️⚠️⚠️ AUTOGENERATED - DO NOT EDIT MANUALLY   ⚠️⚠️⚠️
// ⚠️⚠️⚠️ Updated by COSMIC and GAIA on each run ⚠️⚠️⚠️
// ============================================================================

export interface ProcessingRecord {
  id: string;
  timestamp: string;
  system: 'COSMIC' | 'GAIA';
  totalFilesGenerated: number;
  totalTimeMs: number;
  averageTimePerFile: number;
  cacheHits: number;
  cacheMisses: number;
  memoryUsage: number;
  fileTypeBreakdown: Record<string, number>;
}

export interface ResourceProfile {
  fileType: string;
  averageGenerationTimeMs: number;
  typicalSize: number;
  dependencies: string[];
}

export const EFFICIENCY_RECORDS: ProcessingRecord[] = ${JSON.stringify(EFFICIENCY_RECORDS, null, 2)};

export const RESOURCE_PROFILES: ResourceProfile[] = ${JSON.stringify(RESOURCE_PROFILES, null, 2)};
`;

  fs.writeFileSync(RECORDS_PATH, content, 'utf-8');
}

// Load on module initialization
loadRecords();

// ============================================================================
// HELPER FUNCTIONS
// ============================================================================

/**
 * Add a processing record
 */
export function addRecord(record: ProcessingRecord): void {
  EFFICIENCY_RECORDS.unshift(record);
  
  // Maintain max 1000 records
  if (EFFICIENCY_RECORDS.length > 1000) {
    EFFICIENCY_RECORDS = EFFICIENCY_RECORDS.slice(0, 1000);
  }
  
  saveRecords();
}

/**
 * Get average times for file types
 */
export function getAverageTimes(): Record<string, number> {
  const averages: Record<string, { total: number; count: number }> = {};
  
  for (const record of EFFICIENCY_RECORDS) {
    for (const [fileType, count] of Object.entries(record.fileTypeBreakdown)) {
      if (!averages[fileType]) {
        averages[fileType] = { total: 0, count: 0 };
      }
      averages[fileType].total += record.averageTimePerFile * count;
      averages[fileType].count += count;
    }
  }
  
  const result: Record<string, number> = {};
  for (const [fileType, data] of Object.entries(averages)) {
    result[fileType] = data.count > 0 ? data.total / data.count : 0;
  }
  
  return result;
}

/**
 * Update resource profile based on actual data
 */
export function updateResourceProfile(fileType: string, actualTimeMs: number, actualSize: number): void {
  const profile = RESOURCE_PROFILES.find(p => p.fileType === fileType);
  if (profile) {
    // Weighted average (80% existing, 20% new)
    profile.averageGenerationTimeMs = profile.averageGenerationTimeMs * 0.8 + actualTimeMs * 0.2;
    profile.typicalSize = profile.typicalSize * 0.8 + actualSize * 0.2;
    saveRecords();
  }
}

/**
 * Get estimated time for a generation run
 */
export function estimateRunTime(fileTypes: Record<string, number>): number {
  let total = 0;
  for (const [fileType, count] of Object.entries(fileTypes)) {
    const profile = RESOURCE_PROFILES.find(p => p.fileType === fileType);
    if (profile) {
      total += profile.averageGenerationTimeMs * count;
    }
  }
  return total;
}

/**
 * Get efficiency statistics
 */
export function getEfficiencyStats(): {
  averageTotalTime: number;
  fastestRun: ProcessingRecord | null;
  slowestRun: ProcessingRecord | null;
  totalFilesGenerated: number;
  totalRuns: number;
} {
  if (EFFICIENCY_RECORDS.length === 0) {
    return {
      averageTotalTime: 0,
      fastestRun: null,
      slowestRun: null,
      totalFilesGenerated: 0,
      totalRuns: 0
    };
  }
  
  let totalTime = 0;
  let fastest = EFFICIENCY_RECORDS[0];
  let slowest = EFFICIENCY_RECORDS[0];
  let totalFiles = 0;
  
  for (const record of EFFICIENCY_RECORDS) {
    totalTime += record.totalTimeMs;
    totalFiles += record.totalFilesGenerated;
    if (record.totalTimeMs < fastest.totalTimeMs) fastest = record;
    if (record.totalTimeMs > slowest.totalTimeMs) slowest = record;
  }
  
  return {
    averageTotalTime: totalTime / EFFICIENCY_RECORDS.length,
    fastestRun: fastest,
    slowestRun: slowest,
    totalFilesGenerated: totalFiles,
    totalRuns: EFFICIENCY_RECORDS.length
  };
}