// src/config/enum_mapping.ts
// ============================================================================
// ENUM MAPPING - AUTOGENERATED - DO NOT EDIT MANUALLY
// ============================================================================
// Generated by GAIA on 2026-04-15T01:19:25.670Z
// Maps each enum to the deity folder of the highest priority table that references it
// ============================================================================

export interface EnumMappingEntry {
  enumName: string;
  deityFolder: string;
  referencedIn: string[];
  priority: number;
}

export const ENUM_MAPPING: Record<string, EnumMappingEntry> = {
  "acid_question_type": {
    "enumName": "acid_question_type",
    "deityFolder": "mnemosyne-assessment",
    "referencedIn": [
      "acid_test_questions"
    ],
    "priority": 60
  },
  "acid_persona": {
    "enumName": "acid_persona",
    "deityFolder": "mnemosyne-assessment",
    "referencedIn": [
      "acid_test_results"
    ],
    "priority": 60
  },
  "user_tier": {
    "enumName": "user_tier",
    "deityFolder": "hestia-core",
    "referencedIn": [
      "acid_test_results",
      "profiles",
      "sales"
    ],
    "priority": 100
  },
  "action_type": {
    "enumName": "action_type",
    "deityFolder": "hermes-social",
    "referencedIn": [
      "activity"
    ],
    "priority": 80
  },
  "target_type": {
    "enumName": "target_type",
    "deityFolder": "hermes-social",
    "referencedIn": [
      "activity"
    ],
    "priority": 80
  },
  "activity_visibility": {
    "enumName": "activity_visibility",
    "deityFolder": "hermes-social",
    "referencedIn": [
      "activity"
    ],
    "priority": 80
  },
  "admin_log_category": {
    "enumName": "admin_log_category",
    "deityFolder": "themis-governance",
    "referencedIn": [
      "admin_logs"
    ],
    "priority": 50
  },
  "admin_log_target_type": {
    "enumName": "admin_log_target_type",
    "deityFolder": "themis-governance",
    "referencedIn": [
      "admin_logs"
    ],
    "priority": 50
  },
  "bid_type": {
    "enumName": "bid_type",
    "deityFolder": "plutus-economics",
    "referencedIn": [
      "advertising"
    ],
    "priority": 90
  },
  "campaign_status": {
    "enumName": "campaign_status",
    "deityFolder": "plutus-economics",
    "referencedIn": [
      "advertising"
    ],
    "priority": 90
  },
  "bridge_status": {
    "enumName": "bridge_status",
    "deityFolder": "aethelred-connections",
    "referencedIn": [
      "aethelred_house"
    ],
    "priority": 20
  },
  "analytics_category": {
    "enumName": "analytics_category",
    "deityFolder": "hephaestus-infrastructure",
    "referencedIn": [
      "analytics"
    ],
    "priority": 30
  },
  "application_type": {
    "enumName": "application_type",
    "deityFolder": "themis-governance",
    "referencedIn": [
      "applications"
    ],
    "priority": 50
  },
  "application_status": {
    "enumName": "application_status",
    "deityFolder": "themis-governance",
    "referencedIn": [
      "applications"
    ],
    "priority": 50
  },
  "platform_environment": {
    "enumName": "platform_environment",
    "deityFolder": "aethelred-connections",
    "referencedIn": [
      "audhdities_platform"
    ],
    "priority": 20
  },
  "platform_status": {
    "enumName": "platform_status",
    "deityFolder": "aethelred-connections",
    "referencedIn": [
      "audhdities_platform"
    ],
    "priority": 20
  },
  "badge_type": {
    "enumName": "badge_type",
    "deityFolder": "athena-gamification",
    "referencedIn": [
      "badges"
    ],
    "priority": 70
  },
  "council_house": {
    "enumName": "council_house",
    "deityFolder": "hestia-core",
    "referencedIn": [
      "badges",
      "calendar",
      "community_profiles",
      "learning_paths",
      "mythology",
      "profiles",
      "quests",
      "scenes",
      "surveys"
    ],
    "priority": 100
  },
  "badge_rarity": {
    "enumName": "badge_rarity",
    "deityFolder": "athena-gamification",
    "referencedIn": [
      "badges"
    ],
    "priority": 70
  },
  "badge_tier": {
    "enumName": "badge_tier",
    "deityFolder": "athena-gamification",
    "referencedIn": [
      "badges"
    ],
    "priority": 70
  },
  "calendar_event_type": {
    "enumName": "calendar_event_type",
    "deityFolder": "hephaestus-infrastructure",
    "referencedIn": [
      "calendar"
    ],
    "priority": 30
  },
  "calendar_visibility": {
    "enumName": "calendar_visibility",
    "deityFolder": "hephaestus-infrastructure",
    "referencedIn": [
      "calendar"
    ],
    "priority": 30
  },
  "content_rating": {
    "enumName": "content_rating",
    "deityFolder": "hestia-core",
    "referencedIn": [
      "channels"
    ],
    "priority": 100
  },
  "communication_style": {
    "enumName": "communication_style",
    "deityFolder": "hestia-core",
    "referencedIn": [
      "community_profiles"
    ],
    "priority": 100
  },
  "contact_direction": {
    "enumName": "contact_direction",
    "deityFolder": "iris-communications",
    "referencedIn": [
      "contact_submissions"
    ],
    "priority": 40
  },
  "contact_status": {
    "enumName": "contact_status",
    "deityFolder": "iris-communications",
    "referencedIn": [
      "contact_submissions"
    ],
    "priority": 40
  },
  "contribution_type": {
    "enumName": "contribution_type",
    "deityFolder": "plutus-economics",
    "referencedIn": [
      "contributions"
    ],
    "priority": 90
  },
  "verification_status": {
    "enumName": "verification_status",
    "deityFolder": "hestia-core",
    "referencedIn": [
      "creator_profiles",
      "vendor_profiles"
    ],
    "priority": 100
  },
  "currency_position_type": {
    "enumName": "currency_position_type",
    "deityFolder": "iris-communications",
    "referencedIn": [
      "culturalization"
    ],
    "priority": 40
  },
  "date_format_type": {
    "enumName": "date_format_type",
    "deityFolder": "iris-communications",
    "referencedIn": [
      "culturalization"
    ],
    "priority": 40
  },
  "measurement_system_type": {
    "enumName": "measurement_system_type",
    "deityFolder": "iris-communications",
    "referencedIn": [
      "culturalization"
    ],
    "priority": 40
  },
  "time_format_type": {
    "enumName": "time_format_type",
    "deityFolder": "iris-communications",
    "referencedIn": [
      "culturalization"
    ],
    "priority": 40
  },
  "custom_category_type": {
    "enumName": "custom_category_type",
    "deityFolder": "iris-communications",
    "referencedIn": [
      "customs"
    ],
    "priority": 40
  },
  "source_pool_type": {
    "enumName": "source_pool_type",
    "deityFolder": "plutus-economics",
    "referencedIn": [
      "disbursements"
    ],
    "priority": 90
  },
  "payout_status": {
    "enumName": "payout_status",
    "deityFolder": "plutus-economics",
    "referencedIn": [
      "disbursements",
      "payouts",
      "residual_payouts"
    ],
    "priority": 90
  },
  "email_status": {
    "enumName": "email_status",
    "deityFolder": "iris-communications",
    "referencedIn": [
      "email_communications"
    ],
    "priority": 40
  },
  "emerald_status": {
    "enumName": "emerald_status",
    "deityFolder": "hermes-social",
    "referencedIn": [
      "emeralds"
    ],
    "priority": 80
  },
  "folksonomy_target_type": {
    "enumName": "folksonomy_target_type",
    "deityFolder": "mnemosyne-assessment",
    "referencedIn": [
      "folksonomy"
    ],
    "priority": 60
  },
  "workflow_status": {
    "enumName": "workflow_status",
    "deityFolder": "aethelred-connections",
    "referencedIn": [
      "github_connection"
    ],
    "priority": 20
  },
  "text_direction_type": {
    "enumName": "text_direction_type",
    "deityFolder": "iris-communications",
    "referencedIn": [
      "languages"
    ],
    "priority": 40
  },
  "difficulty_level": {
    "enumName": "difficulty_level",
    "deityFolder": "athena-gamification",
    "referencedIn": [
      "learning_paths"
    ],
    "priority": 70
  },
  "ledger_entry_type": {
    "enumName": "ledger_entry_type",
    "deityFolder": "plutus-economics",
    "referencedIn": [
      "ledger"
    ],
    "priority": 90
  },
  "ledger_entity": {
    "enumName": "ledger_entity",
    "deityFolder": "plutus-economics",
    "referencedIn": [
      "ledger"
    ],
    "priority": 90
  },
  "lesson_content_type": {
    "enumName": "lesson_content_type",
    "deityFolder": "athena-gamification",
    "referencedIn": [
      "lessons"
    ],
    "priority": 70
  },
  "life_cycle_phase": {
    "enumName": "life_cycle_phase",
    "deityFolder": "athena-gamification",
    "referencedIn": [
      "life_cycles"
    ],
    "priority": 70
  },
  "maintenance_status": {
    "enumName": "maintenance_status",
    "deityFolder": "hephaestus-infrastructure",
    "referencedIn": [
      "maintenance"
    ],
    "priority": 30
  },
  "maintenance_type": {
    "enumName": "maintenance_type",
    "deityFolder": "hephaestus-infrastructure",
    "referencedIn": [
      "maintenance"
    ],
    "priority": 30
  },
  "message_status": {
    "enumName": "message_status",
    "deityFolder": "hermes-social",
    "referencedIn": [
      "messages"
    ],
    "priority": 80
  },
  "moderation_action_type": {
    "enumName": "moderation_action_type",
    "deityFolder": "themis-governance",
    "referencedIn": [
      "moderation_actions"
    ],
    "priority": 50
  },
  "moderation_target_type": {
    "enumName": "moderation_target_type",
    "deityFolder": "themis-governance",
    "referencedIn": [
      "moderation_actions"
    ],
    "priority": 50
  },
  "myth_type": {
    "enumName": "myth_type",
    "deityFolder": "athena-gamification",
    "referencedIn": [
      "mythology"
    ],
    "priority": 70
  },
  "notification_type": {
    "enumName": "notification_type",
    "deityFolder": "hermes-social",
    "referencedIn": [
      "notifications"
    ],
    "priority": 80
  },
  "ontology_predicate": {
    "enumName": "ontology_predicate",
    "deityFolder": "mnemosyne-assessment",
    "referencedIn": [
      "ontology"
    ],
    "priority": 60
  },
  "payout_method": {
    "enumName": "payout_method",
    "deityFolder": "hestia-core",
    "referencedIn": [
      "payouts",
      "user_financial"
    ],
    "priority": 100
  },
  "content_type": {
    "enumName": "content_type",
    "deityFolder": "hermes-social",
    "referencedIn": [
      "posts"
    ],
    "priority": 80
  },
  "post_visibility": {
    "enumName": "post_visibility",
    "deityFolder": "hermes-social",
    "referencedIn": [
      "posts"
    ],
    "priority": 80
  },
  "escalation_target": {
    "enumName": "escalation_target",
    "deityFolder": "themis-governance",
    "referencedIn": [
      "processes"
    ],
    "priority": 50
  },
  "process_type": {
    "enumName": "process_type",
    "deityFolder": "themis-governance",
    "referencedIn": [
      "processes"
    ],
    "priority": 50
  },
  "owner_type": {
    "enumName": "owner_type",
    "deityFolder": "plutus-economics",
    "referencedIn": [
      "products"
    ],
    "priority": 90
  },
  "product_type": {
    "enumName": "product_type",
    "deityFolder": "plutus-economics",
    "referencedIn": [
      "products"
    ],
    "priority": 90
  },
  "recurring_interval": {
    "enumName": "recurring_interval",
    "deityFolder": "plutus-economics",
    "referencedIn": [
      "products"
    ],
    "priority": 90
  },
  "user_status": {
    "enumName": "user_status",
    "deityFolder": "hestia-core",
    "referencedIn": [
      "profiles"
    ],
    "priority": 100
  },
  "progress_status": {
    "enumName": "progress_status",
    "deityFolder": "athena-gamification",
    "referencedIn": [
      "progress"
    ],
    "priority": 70
  },
  "blueprint_status": {
    "enumName": "blueprint_status",
    "deityFolder": "prometheus-meta",
    "referencedIn": [
      "prometheus_blueprints"
    ],
    "priority": 0
  },
  "blueprint_system": {
    "enumName": "blueprint_system",
    "deityFolder": "prometheus-meta",
    "referencedIn": [
      "prometheus_blueprints"
    ],
    "priority": 0
  },
  "encryption_level": {
    "enumName": "encryption_level",
    "deityFolder": "prometheus-meta",
    "referencedIn": [
      "prometheus_boundaries"
    ],
    "priority": 0
  },
  "boundary_type": {
    "enumName": "boundary_type",
    "deityFolder": "prometheus-meta",
    "referencedIn": [
      "prometheus_boundaries"
    ],
    "priority": 0
  },
  "consciousness_state": {
    "enumName": "consciousness_state",
    "deityFolder": "prometheus-meta",
    "referencedIn": [
      "prometheus_consciousness"
    ],
    "priority": 0
  },
  "generation_status": {
    "enumName": "generation_status",
    "deityFolder": "prometheus-meta",
    "referencedIn": [
      "prometheus_generations"
    ],
    "priority": 0
  },
  "pattern_context": {
    "enumName": "pattern_context",
    "deityFolder": "prometheus-meta",
    "referencedIn": [
      "prometheus_patterns",
      "prometheus_templates"
    ],
    "priority": 0
  },
  "protocol_type": {
    "enumName": "protocol_type",
    "deityFolder": "hephaestus-infrastructure",
    "referencedIn": [
      "protocols"
    ],
    "priority": 30
  },
  "submission_type": {
    "enumName": "submission_type",
    "deityFolder": "athena-gamification",
    "referencedIn": [
      "quests"
    ],
    "priority": 70
  },
  "reaction_type": {
    "enumName": "reaction_type",
    "deityFolder": "hermes-social",
    "referencedIn": [
      "reactions"
    ],
    "priority": 80
  },
  "report_type": {
    "enumName": "report_type",
    "deityFolder": "themis-governance",
    "referencedIn": [
      "reports"
    ],
    "priority": 50
  },
  "report_status": {
    "enumName": "report_status",
    "deityFolder": "themis-governance",
    "referencedIn": [
      "reports"
    ],
    "priority": 50
  },
  "report_target_type": {
    "enumName": "report_target_type",
    "deityFolder": "themis-governance",
    "referencedIn": [
      "reports"
    ],
    "priority": 50
  },
  "delivery_status": {
    "enumName": "delivery_status",
    "deityFolder": "aethelred-connections",
    "referencedIn": [
      "resend_connection"
    ],
    "priority": 20
  },
  "payment_status": {
    "enumName": "payment_status",
    "deityFolder": "plutus-economics",
    "referencedIn": [
      "sales",
      "transactions"
    ],
    "priority": 90
  },
  "scene_type": {
    "enumName": "scene_type",
    "deityFolder": "athena-gamification",
    "referencedIn": [
      "scenes"
    ],
    "priority": 70
  },
  "job_type": {
    "enumName": "job_type",
    "deityFolder": "hephaestus-infrastructure",
    "referencedIn": [
      "scheduling"
    ],
    "priority": 30
  },
  "job_status": {
    "enumName": "job_status",
    "deityFolder": "hephaestus-infrastructure",
    "referencedIn": [
      "scheduling"
    ],
    "priority": 30
  },
  "script_type": {
    "enumName": "script_type",
    "deityFolder": "hephaestus-infrastructure",
    "referencedIn": [
      "scripts"
    ],
    "priority": 30
  },
  "setting_scope": {
    "enumName": "setting_scope",
    "deityFolder": "hephaestus-infrastructure",
    "referencedIn": [
      "settings"
    ],
    "priority": 30
  },
  "stripe_mode": {
    "enumName": "stripe_mode",
    "deityFolder": "aethelred-connections",
    "referencedIn": [
      "stripe_connection"
    ],
    "priority": 20
  },
  "webhook_status": {
    "enumName": "webhook_status",
    "deityFolder": "aethelred-connections",
    "referencedIn": [
      "stripe_connection"
    ],
    "priority": 20
  },
  "subscription_status": {
    "enumName": "subscription_status",
    "deityFolder": "plutus-economics",
    "referencedIn": [
      "subscriptions"
    ],
    "priority": 90
  },
  "supabase_status": {
    "enumName": "supabase_status",
    "deityFolder": "aethelred-connections",
    "referencedIn": [
      "supabase_connection"
    ],
    "priority": 20
  },
  "superposition_status": {
    "enumName": "superposition_status",
    "deityFolder": "mnemosyne-assessment",
    "referencedIn": [
      "superposition"
    ],
    "priority": 60
  },
  "survey_audience_type": {
    "enumName": "survey_audience_type",
    "deityFolder": "iris-communications",
    "referencedIn": [
      "surveys"
    ],
    "priority": 40
  },
  "system_status": {
    "enumName": "system_status",
    "deityFolder": "hephaestus-infrastructure",
    "referencedIn": [
      "system_health_logs",
      "systems"
    ],
    "priority": 30
  },
  "system_type": {
    "enumName": "system_type",
    "deityFolder": "hephaestus-infrastructure",
    "referencedIn": [
      "systems"
    ],
    "priority": 30
  },
  "taxonomy_node_type": {
    "enumName": "taxonomy_node_type",
    "deityFolder": "mnemosyne-assessment",
    "referencedIn": [
      "taxonomy"
    ],
    "priority": 60
  },
  "timeline_event_type": {
    "enumName": "timeline_event_type",
    "deityFolder": "athena-gamification",
    "referencedIn": [
      "timelines"
    ],
    "priority": 70
  },
  "transaction_type": {
    "enumName": "transaction_type",
    "deityFolder": "plutus-economics",
    "referencedIn": [
      "transactions"
    ],
    "priority": 90
  },
  "translatable_type": {
    "enumName": "translatable_type",
    "deityFolder": "iris-communications",
    "referencedIn": [
      "translations"
    ],
    "priority": 40
  },
  "payout_frequency": {
    "enumName": "payout_frequency",
    "deityFolder": "hestia-core",
    "referencedIn": [
      "user_financial"
    ],
    "priority": 100
  },
  "quest_status": {
    "enumName": "quest_status",
    "deityFolder": "athena-gamification",
    "referencedIn": [
      "user_quests"
    ],
    "priority": 70
  },
  "business_type": {
    "enumName": "business_type",
    "deityFolder": "hestia-core",
    "referencedIn": [
      "vendor_profiles"
    ],
    "priority": 100
  },
  "deployment_status": {
    "enumName": "deployment_status",
    "deityFolder": "aethelred-connections",
    "referencedIn": [
      "vercel_connection"
    ],
    "priority": 20
  },
  "default": {
    "enumName": "default",
    "deityFolder": "hestia-core",
    "referencedIn": [],
    "priority": 0
  }
};

/**
 * Get the deity folder for an enum
 */
export function getEnumFolder(enumName: string): string {
  return ENUM_MAPPING[enumName]?.deityFolder || ENUM_MAPPING.default.deityFolder;
}

/**
 * Get the full mapping entry for an enum
 */
export function getEnumMapping(enumName: string): EnumMappingEntry | undefined {
  return ENUM_MAPPING[enumName];
}

/**
 * Get all enums that belong to a specific deity folder
 */
export function getEnumsByDeity(deityFolder: string): string[] {
  return Object.values(ENUM_MAPPING)
    .filter(entry => entry.deityFolder === deityFolder)
    .map(entry => entry.enumName);
}
