// src/config/enum_mapping.ts
// ============================================================================
// ENUM MAPPING - AUTOGENERATED - DO NOT EDIT MANUALLY
// ============================================================================
// Generated by GAIA on 2026-08-01T17:49:49.189Z
// Maps each enum to the deity folder of the highest priority table that references it
// ============================================================================

export interface EnumMappingEntry {
  enumName: string;
  deityFolder: string;
  referencedIn: string[];
  priority: number;
}

export const ENUM_MAPPING: Record<string, EnumMappingEntry> = {
  "application_type": {
    "enumName": "application_type",
    "deityFolder": "themis-governance",
    "referencedIn": [
      "applications"
    ],
    "priority": 50
  },
  "application_status": {
    "enumName": "application_status",
    "deityFolder": "themis-governance",
    "referencedIn": [
      "applications",
      "proposals",
      "reports"
    ],
    "priority": 50
  },
  "profile_status": {
    "enumName": "profile_status",
    "deityFolder": "hestia-core",
    "referencedIn": [
      "artisan_profiles",
      "community_profiles",
      "merchant_profiles"
    ],
    "priority": 100
  },
  "content_status": {
    "enumName": "content_status",
    "deityFolder": "hestia-core",
    "referencedIn": [
      "assessment_questions",
      "blueprints",
      "boundaries",
      "bubble_superposition",
      "bubbles",
      "calendar",
      "channels",
      "collection_items",
      "collection_sets",
      "contact_submissions",
      "council_houses",
      "email_communications",
      "energy_entries",
      "events",
      "file_registry",
      "file_type_standards",
      "folksonomy",
      "garden_plots",
      "gift_wrappings",
      "grant_attachments",
      "grant_narratives",
      "grant_opportunities",
      "journal_entries",
      "learning_paths",
      "lessons",
      "life_cycles",
      "maintenance",
      "messages",
      "mythology",
      "patronage_tiers",
      "personas",
      "plant_stages",
      "platform_config",
      "processes",
      "protocols",
      "quests",
      "rate_limits",
      "reference_values",
      "responses",
      "scenes",
      "scheduling",
      "seed_types",
      "sigil_unlocks",
      "sigils",
      "signals",
      "surveys",
      "vessel_anchors",
      "vessel_companions",
      "vessel_decorations",
      "vessel_exteriors",
      "vessel_interiors",
      "vessel_rooms",
      "wares",
      "works"
    ],
    "priority": 100
  },
  "sovereign_tier": {
    "enumName": "sovereign_tier",
    "deityFolder": "hestia-core",
    "referencedIn": [
      "community_profiles"
    ],
    "priority": 100
  },
  "exchange_status": {
    "enumName": "exchange_status",
    "deityFolder": "plutus-economics",
    "referencedIn": [
      "exchanges"
    ],
    "priority": 90
  },
  "notification_channel": {
    "enumName": "notification_channel",
    "deityFolder": "hestia-core",
    "referencedIn": [
      "heralds",
      "vessel_config"
    ],
    "priority": 100
  },
  "user_role": {
    "enumName": "user_role",
    "deityFolder": "hestia-core",
    "referencedIn": [
      "user_roles"
    ],
    "priority": 100
  },
  "herald_digest": {
    "enumName": "herald_digest",
    "deityFolder": "hestia-core",
    "referencedIn": [
      "vessel_config"
    ],
    "priority": 100
  },
  "display_theme": {
    "enumName": "display_theme",
    "deityFolder": "hestia-core",
    "referencedIn": [
      "vessel_config"
    ],
    "priority": 100
  },
  "pricing_model": {
    "enumName": "pricing_model",
    "deityFolder": "plutus-economics",
    "referencedIn": [
      "wares",
      "works"
    ],
    "priority": 90
  },
  "ware_type": {
    "enumName": "ware_type",
    "deityFolder": "plutus-economics",
    "referencedIn": [
      "wares"
    ],
    "priority": 90
  },
  "work_type": {
    "enumName": "work_type",
    "deityFolder": "hermes-social",
    "referencedIn": [
      "works"
    ],
    "priority": 80
  },
  "default": {
    "enumName": "default",
    "deityFolder": "hestia-core",
    "referencedIn": [
    ],
    "priority": 0
  },
};

/**
 * Get the deity folder for an enum
 */
export function getEnumFolder(enumName: string): string {
  return ENUM_MAPPING[enumName]?.deityFolder || ENUM_MAPPING.default.deityFolder;
}

/**
 * Get the full mapping entry for an enum
 */
export function getEnumMapping(enumName: string): EnumMappingEntry | undefined {
  return ENUM_MAPPING[enumName];
}

/**
 * Get all enums that belong to a specific deity folder
 */
export function getEnumsByDeity(deityFolder: string): string[] {
  return Object.values(ENUM_MAPPING)
    .filter(entry => entry.deityFolder === deityFolder)
    .map(entry => entry.enumName);
}
