// ============================================================================
// Central registry for all system activity, generated files, and run history
// "⚠️⚠️⚠️" src/config/system-registry.ts          "⚠️⚠️⚠️"
// "⚠️⚠️⚠️" AUTOGENERATED - DO NOT EDIT MANUALLY   "⚠️⚠️⚠️"
// "⚠️⚠️⚠️" Updated by COSMIC and GAIA on each run "⚠️⚠️⚠️"
// Purpose: Track all system runs and generated files
// ============================================================================

import type { RunRecord } from '../scripts/shared/systemLogger.js';

export interface GeneratedFileRecord {
  path: string;
  system: 'COSMIC' | 'GAIA';
  generatedAt: string;
  sourceFiles: string[];
  lastValidated: string;
  validationStatus: 'valid' | 'stale' | 'conflict';
  fileHash: string;
  dependencies: string[];
  dependents: string[];
}

export interface SystemRegistry {
  version: string;
  updatedAt: string;
  cosmic: {
    lastRun: RunRecord | null;
    runs: RunRecord[];
    files: Record<string, GeneratedFileRecord>;
  };
  gaia: {
    lastRun: RunRecord | null;
    runs: RunRecord[];
    files: Record<string, GeneratedFileRecord>;
  };
  settings: {
    maxRunsToRetain: number;
    autoCorrectEnabled: boolean;
    useFileHashes: boolean;
  };
}

// ============================================================================
// DEFAULT REGISTRY
// ============================================================================

export const SYSTEM_REGISTRY: SystemRegistry = {
  version: '1.0.0',
  updatedAt: new Date().toISOString(),
  cosmic: {
    lastRun: null,
    runs: [],
    files: {}
  },
  gaia: {
    lastRun: null,
    runs: [],
    files: {}
  },
  settings: {
    maxRunsToRetain: 100,
    autoCorrectEnabled: false,
    useFileHashes: true
  }
};

// ============================================================================
// HELPER FUNCTIONS
// ============================================================================

/**
 * Save the registry to disk
 */
export function saveRegistry(registry: SystemRegistry): void {
  // TODO: Write registry to config/system-registry.ts
}

/**
 * Load the registry from disk
 */
export function loadRegistry(): SystemRegistry {
  // TODO: Read registry file if exists, else return default
}

/**
 * Update registry settings
 */
export function updateSettings(settings: Partial<SystemRegistry['settings']>): void {
  // TODO: Merge settings and save
}

/**
 * Prune old runs based on maxRunsToRetain setting
 */
export function pruneOldRuns(registry: SystemRegistry): SystemRegistry {
  // TODO: Remove runs beyond maxRunsToRetain for both cosmic and gaia
}