// @/config/system_registry.ts
// ============================================================================
// SYSTEM REGISTRY - AUTOGENERATED - DO NOT EDIT MANUALLY
// ============================================================================
// Updated by COSMIC and GAIA on each run
// ============================================================================

export interface SystemRegistryFile {
  version: string;
  updatedAt: string;
  cosmic: {
    lastRun: RunRecord | null;
    runs: RunRecord[];
    files: Record<string, { hash: string; generatedAt: string }>;
  };
  gaia: {
    lastRun: RunRecord | null;
    runs: RunRecord[];
    files: Record<string, { hash: string; generatedAt: string }>;
  };
  settings: {
    maxRunsToRetain: number;
    autoCorrectEnabled: boolean;
    useFileHashes: boolean;
  };
}

export interface RunRecord {
  id: string;
  system: 'COSMIC' | 'GAIA';
  startTime: string;
  endTime: string;
  status: 'success' | 'partial' | 'failed';
  generatedFiles: string[];
  errors: string[];
  warnings: string[];
  notes: string[];
}

export const SYSTEM_REGISTRY: SystemRegistryFile = {
  "version": "1.0.0",
  "updatedAt": "2026-04-19T21:08:22.234Z",
  "cosmic": {
    "lastRun": null,
    "runs": [],
    "files": {}
  },
  "gaia": {
    "lastRun": {
      "id": "20260419_160819",
      "system": "GAIA",
      "startTime": "2026-04-19T21:08:19.125Z",
      "endTime": "2026-04-19T21:08:22.233Z",
      "status": "success",
      "generatedFiles": [],
      "errors": [],
      "warnings": [],
      "notes": [
        "Found 110 tables, 4 views, 53 functions, 114 enums",
        "Directory discovery: 532 existing files found",
        "Extracted: 110 tables, 4 views, 53 functions, 114 runtime enums"
      ]
    },
    "runs": [],
    "files": {}
  },
  "settings": {
    "maxRunsToRetain": 100,
    "autoCorrectEnabled": false,
    "useFileHashes": true
  }
};
