// @/components/ui/variants/button-group.ts
// GENERATED BY DESIGN SYSTEM - DO NOT EDIT MANUALLY

export const buttonGroupVariants = {
  // Layout variants (structural, not visual)
  horizontal: "flex-row",
  vertical: "flex-col",
  
  // Spacing variants
  spaced: "gap-4",
  default: "gap-2",
  compact: "gap-1",
  
  // Visual variants (from design system)
  quantum: "[&>*]:border-quantum-purple [&>*]:bg-quantum-purple/10",
  cosmic: "[&>*]:border-cosmic-blue [&>*]:bg-cosmic-blue/10",
  hearth: "[&>*]:border-hearth-gold [&>*]:bg-hearth-gold/10",
  
  // Child button modifiers
  joined: "[&>*:not(:first-child)]:rounded-l-none [&>*:not(:last-child)]:rounded-r-none [&>*]:border-l-0 first:[&>*]:border-l",
}