// @/components/ui/variants/button.ts
// GENERATED BY DESIGN SYSTEM - DO NOT EDIT MANUALLY
// These classes will be generated from our constants/colors.ts

export const buttonVariants = {
  // Variants
  primary: "bg-quantum-purple text-white hover:bg-quantum-dark focus:ring-quantum-light",
  secondary: "bg-cosmic-blue text-white hover:bg-cosmic-dark focus:ring-cosmic-light",
  outline: "border border-star-dust/20 bg-transparent hover:bg-star-dust/10",
  ghost: "hover:bg-star-dust/10",
  destructive: "bg-fire-base text-white hover:bg-fire-dark",
  success: "bg-sanctuary-green text-white hover:bg-sanctuary-emerald",
  warning: "bg-hearth-gold text-deep-space hover:bg-hearth-orange",
  
  // Sizes
  xs: "text-xs px-2 py-1 rounded-sm",
  sm: "text-sm px-3 py-1.5 rounded-md",
  md: "text-base px-4 py-2 rounded-lg",
  lg: "text-lg px-6 py-3 rounded-xl",
  xl: "text-xl px-8 py-4 rounded-2xl",
  
  // Icon sizes
  iconXs: "p-1 rounded-sm",
  iconSm: "p-1.5 rounded-md",
  iconMd: "p-2 rounded-lg",
  iconLg: "p-3 rounded-xl",
  
  // Full width
  fullWidth: "w-full",
  
  // Loading state
  loading: "opacity-70 cursor-wait",
  
  // Disabled state
  disabled: "opacity-50 cursor-not-allowed",
}