// src/scripts/system/gaia/generate/validator_builder.ts
// ============================================================================
// VALIDATOR BUILDER - Sequential Line-by-Line Zod Schema Builder
// ============================================================================

import * as fs from 'fs';
import * as path from 'path';
import { fileURLToPath } from 'url';
import { 
  TYPE_MAPPINGS, 
  FIELD_NAME_OVERRIDES,
  AUTO_GENERATED_FIELDS,
  findZodType,
  findFieldNameOverride,
  isAutoGeneratedField,
  applyModifiers,
  toCamelCase,
  toPascalCase
} from '../../../shared/type_mappings.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const PROJECT_ROOT = path.resolve(__dirname, '../../../../..');

// ============================================================================
// TYPES
// ============================================================================

export interface ValidatorBuilderResult {
  rowSchema: string;
  insertSchema: string;
  updateSchema: string;
  enumImports: string[];
  fieldCount: number;
  hasEnums: boolean; 
}

interface ParsedTypeField {
  name: string;
  tsType: string;
  isNullable: boolean;
  isOptional: boolean;
  isEnum: boolean;
  enumName?: string;
}

// ============================================================================
// TYPE FILE PARSING
// ============================================================================

function parseTypeFile(typeFilePath: string, tableName: string): ParsedTypeField[] | null {
  try {
    const content = fs.readFileSync(typeFilePath, 'utf-8');
    const pascalName = toPascalCase(tableName);
    
    // Look for AllFields interface
    const allFieldsPattern = new RegExp(`export interface ${pascalName}AllFields\\s*{([^}]*(?:{[^}]*}[^}]*)*)}`, 's');
    const match = content.match(allFieldsPattern);
    
    if (!match) {
      console.warn(`AllFields interface not found for ${tableName}`);
      return null;
    }
    
    const interfaceContent = match[1];
    const fields: ParsedTypeField[] = [];
    const lines = interfaceContent.split('\n');
    
    for (const line of lines) {
      const fieldMatch = line.match(/^\s*(\w+)(\?)?:\s*(.+?);/);
      if (!fieldMatch) continue;
      
      const fieldName = fieldMatch[1];
      const hasQuestionMark = fieldMatch[2] === '?';
      let tsType = fieldMatch[3].trim();
      
      const isNullable = tsType.includes('| null') || tsType.includes('null |');
      const isOptional = hasQuestionMark || isAutoGeneratedField(fieldName);
      
      tsType = tsType.replace(/\| null/g, '').replace(/null \|/g, '').trim();
      
      const isEnum = !tsType.includes("'") && 
                     !['string', 'number', 'boolean', 'any', 'unknown', 'void', 'Date', 'Json'].includes(tsType) &&
                     !tsType.includes('[]') &&
                     !tsType.includes('{');

      fields.push({
        name: fieldName,
        tsType,
        isNullable,
        isOptional,
        isEnum,
        enumName: isEnum ? tsType.replace(/([A-Z])/g, '_$1').toLowerCase().replace(/^_/, '') : undefined,
      });
    }
    
    return fields;
    
  } catch (error) {
    console.error(`Failed to parse type file ${typeFilePath}:`, error);
    return null;
  }
}

// ============================================================================
// ZOD TYPE CONVERSION
// ============================================================================

function fieldToZodLine(field: ParsedTypeField, indent: string = '  '): string {
  let zodType: string;
  
  const override = findFieldNameOverride(field.name);
  if (override) {
    zodType = override;
  } else if (field.isEnum && field.enumName) {
    const camelName = toCamelCase(field.enumName);
    zodType = `z.enum(ENUM_VALUES["${camelName}"])`;
  } else if (field.tsType.endsWith('[]')) {
    const baseType = field.tsType.slice(0, -2);
    const baseZod = findZodType(baseType) || 'z.any()';
    zodType = `z.array(${baseZod})`;
  } else {
    zodType = findZodType(field.tsType) || 'z.any()';
  }
  
  zodType = applyModifiers(zodType, field.isNullable, field.isOptional);
  
  return `${indent}${field.name}: ${zodType},`;
}

function buildSchemas(fields: ParsedTypeField[], tableName: string): ValidatorBuilderResult {
  const pascalName = toPascalCase(tableName);
  const enumImports: string[] = [];
  
  for (const field of fields) {
    if (field.isEnum && field.enumName) {
      enumImports.push(`ENUM_VALUES.${field.enumName}`);
    }
  }
  
  const rowLines: string[] = [];
  for (const field of fields) {
    rowLines.push(fieldToZodLine(field, '  '));
  }
  
  const insertFields = fields.filter(f => !isAutoGeneratedField(f.name));
  const insertLines: string[] = [];
  for (const field of insertFields) {
    insertLines.push(fieldToZodLine(field, '  '));
  }
  
  const updateLines: string[] = [];
  for (const field of fields) {
    const optionalField = { ...field, isOptional: true };
    updateLines.push(fieldToZodLine(optionalField, '  '));
  }
  
  const rowSchema = `export const ${pascalName}RowSchema = z.object({\n${rowLines.join('\n')}\n});`;
  const insertSchema = `export const ${pascalName}InsertSchema = z.object({\n${insertLines.join('\n')}\n});`;
  const updateSchema = `export const ${pascalName}UpdateSchema = z.object({\n${updateLines.join('\n')}\n});`;
  const hasEnums = fields.some(f => f.isEnum);

  return { rowSchema, insertSchema, updateSchema, enumImports, hasEnums, fieldCount: fields.length };
}

// ============================================================================
// MAIN BUILDER FUNCTION
// ============================================================================

export function buildValidatorFromTypeFile(tableName: string, deityFolder: string): ValidatorBuilderResult | null {
  const typeFilePath = path.join(PROJECT_ROOT, 'src/types/generated', deityFolder, `${tableName}.ts`);
  
  if (!fs.existsSync(typeFilePath)) {
    console.warn(`Type file not found: ${typeFilePath}`);
    return null;
  }
  
  const fields = parseTypeFile(typeFilePath, tableName);
  
  if (!fields || fields.length === 0) {
    console.warn(`Could not parse fields from ${typeFilePath}`);
    return null;
  }
  
  return buildSchemas(fields, tableName);
}

export async function generateValidatorContent(tableName: string, deityFolder: string, handlingLevel: string): Promise<string | null> {
  const result = buildValidatorFromTypeFile(tableName, deityFolder);
  
  if (!result) return null;
  
  const pascalName = toPascalCase(tableName);
  const timestamp = new Date().toISOString();
  
  let imports = `import { z } from 'zod';\n`;
  if (result.hasEnums) {
    imports += `import { ENUM_VALUES } from '@/types/supabase/enums';\n`;
  }
  
  let content = `// =====================================================
// FILE: lib/validators/generated/${deityFolder}/${tableName}.ts
// HANDLING: ${handlingLevel}
// GENERATED: ${timestamp}
// BUILT FROM: types/generated/${deityFolder}/${tableName}.ts
// =====================================================

${imports}
// =====================================================
// ZOD SCHEMAS (Built from type definitions)
// =====================================================

${result.rowSchema}

${result.insertSchema}

${result.updateSchema}

// =====================================================
// TYPE INFERENCE
// =====================================================

export type ${pascalName}RowInput = z.infer<typeof ${pascalName}RowSchema>;
export type ${pascalName}InsertInput = z.infer<typeof ${pascalName}InsertSchema>;
export type ${pascalName}UpdateInput = z.infer<typeof ${pascalName}UpdateSchema>;

// =====================================================
// VALIDATION UTILITIES
// =====================================================

export function validate${pascalName}Row(data: unknown): data is ${pascalName}RowInput {
  try { ${pascalName}RowSchema.parse(data); return true; } catch { return false; }
}

export function validate${pascalName}Insert(data: unknown): data is ${pascalName}InsertInput {
  try { ${pascalName}InsertSchema.parse(data); return true; } catch { return false; }
}

export function validate${pascalName}Update(data: unknown): data is ${pascalName}UpdateInput {
  try { ${pascalName}UpdateSchema.parse(data); return true; } catch { return false; }
}

export function safeValidate${pascalName}Insert(data: unknown): { success: boolean; data?: ${pascalName}InsertInput; error?: z.ZodError } {
  const result = ${pascalName}InsertSchema.safeParse(data);
  if (result.success) return { success: true, data: result.data };
  return { success: false, error: result.error };
}
`;
  
  return content;
}