// src/scripts/system/gaia/generate/validator_builder.ts
// ============================================================================
// VALIDATOR BUILDER - Sequential Line-by-Line Zod Schema Builder
// ============================================================================
// Purpose: Read generated type files and build Zod schemas sequentially
// Uses: type_mappings.ts, enums.ts (ENUM_VALUES), helper imports
// ============================================================================

import * as fs from 'fs';
import * as path from 'path';
import { fileURLToPath } from 'url';
import { 
  TYPE_MAPPINGS, 
  FIELD_NAME_OVERRIDES,
  AUTO_GENERATED_FIELDS,
  findZodType,
  findFieldNameOverride,
  isAutoGeneratedField,
  applyModifiers,
  toCamelCase,
  toPascalCase,
  type ParsedField 
} from '../../../shared/type_mappings.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const PROJECT_ROOT = path.resolve(__dirname, '../../../..');

// ============================================================================
// TYPES
// ============================================================================

export interface ValidatorBuilderResult {
  rowSchema: string;           // Complete Row Zod schema
  insertSchema: string;        // Complete Insert Zod schema
  updateSchema: string;        // Complete Update Zod schema
  enumImports: string[];       // Enum imports needed (e.g., "ENUM_VALUES.userTier")
  fieldCount: number;
}

interface ParsedTypeField {
  name: string;
  tsType: string;
  isNullable: boolean;
  isOptional: boolean;
  isEnum: boolean;
  enumName?: string;
}

// ============================================================================
// TYPE FILE PARSING
// ============================================================================

/**
 * Parse a generated type file to extract field definitions
 * Reads the Public{Table} interface for complete field information
 */
function parseTypeFile(typeFilePath: string, tableName: string): ParsedTypeField[] | null {
  try {
    const content = fs.readFileSync(typeFilePath, 'utf-8');
    const pascalName = toPascalCase(tableName);
    
    // Find the Public interface (has all fields with proper types)
    const publicInterfacePattern = new RegExp(`export interface Public${pascalName}\\s*{([^}]*(?:{[^}]*}[^}]*)*)}`, 's');
    const match = content.match(publicInterfacePattern);
    
    if (!match) {
      // Fallback to Row type if Public interface not found
      return parseFromRowType(content, tableName);
    }
    
    const interfaceContent = match[1];
    const fields: ParsedTypeField[] = [];
    
    // Parse each field line
    const lines = interfaceContent.split('\n');
    
    for (const line of lines) {
      const fieldMatch = line.match(/^\s*(\w+)(\?)?:\s*(.+?);/);
      if (!fieldMatch) continue;
      
      const fieldName = fieldMatch[1];
      const hasQuestionMark = fieldMatch[2] === '?';
      let tsType = fieldMatch[3].trim();
      
      // Check for nullable
      const isNullable = tsType.includes('| null') || tsType.includes('null |');
      
      // Check for optional
      const isOptional = hasQuestionMark || isAutoGeneratedField(fieldName);
      
      // Clean type
      tsType = tsType
        .replace(/\| null/g, '')
        .replace(/null \|/g, '')
        .trim();
      
      // Check for enum reference (looks like "UserTier" - PascalCase)
      const isEnum = !tsType.includes("'") && 
                     !['string', 'number', 'boolean', 'any', 'unknown', 'void', 'Date', 'Json'].includes(tsType) &&
                     !tsType.includes('[]') &&
                     !tsType.includes('{');
      
      fields.push({
        name: fieldName,
        tsType,
        isNullable,
        isOptional,
        isEnum,
        enumName: isEnum ? tsType.toLowerCase().replace(/([A-Z])/g, '_$1').toLowerCase().replace(/^_/, '') : undefined,
      });
    }
    
    return fields;
    
  } catch (error) {
    console.error(`Failed to parse type file ${typeFilePath}:`, error);
    return null;
  }
}

/**
 * Fallback: Parse from Row type if Public interface not available
 */
function parseFromRowType(content: string, tableName: string): ParsedTypeField[] | null {
  const pascalName = toPascalCase(tableName);
  const rowPattern = new RegExp(`export type ${pascalName}Row = Tables<'${tableName}'>;`);
  
  if (!rowPattern.test(content)) {
    return null;
  }
  
  // If we can't parse fields, return empty - will generate placeholder
  return [];
}

// ============================================================================
// ZOD TYPE CONVERSION
// ============================================================================

/**
 * Convert a parsed field to a Zod schema line
 */
function fieldToZodLine(field: ParsedTypeField, indent: string = '  '): string {
  let zodType: string;
  
  // 1. Check field name overrides first
  const override = findFieldNameOverride(field.name);
  if (override) {
    zodType = override;
  }
  // 2. Handle enums
  else if (field.isEnum && field.enumName) {
    const camelName = toCamelCase(field.enumName);
    zodType = `z.enum(ENUM_VALUES.${camelName})`;
  }
  // 3. Handle arrays
  else if (field.tsType.endsWith('[]')) {
    const baseType = field.tsType.slice(0, -2);
    const baseZod = findZodType(baseType) || 'z.any()';
    zodType = `z.array(${baseZod})`;
  }
  // 4. Use type mapping
  else {
    zodType = findZodType(field.tsType) || 'z.any()';
  }
  
  // Apply nullable/optional modifiers
  zodType = applyModifiers(zodType, field.isNullable, field.isOptional);
  
  return `${indent}${field.name}: ${zodType},`;
}

/**
 * Build complete Zod schemas from parsed fields
 */
function buildSchemas(fields: ParsedTypeField[], tableName: string): ValidatorBuilderResult {
  const pascalName = toPascalCase(tableName);
  const enumImports: string[] = [];
  
  // Collect enum imports
  for (const field of fields) {
    if (field.isEnum && field.enumName) {
      const camelName = toCamelCase(field.enumName);
      enumImports.push(`ENUM_VALUES.${camelName}`);
    }
  }
  
  // Row schema (all fields)
  const rowLines: string[] = [];
  for (const field of fields) {
    rowLines.push(fieldToZodLine(field, '  '));
  }
  
  // Insert schema (exclude auto-generated fields)
  const insertFields = fields.filter(f => !isAutoGeneratedField(f.name));
  const insertLines: string[] = [];
  for (const field of insertFields) {
    // Make all fields optional for insert? No, keep required unless nullable
    insertLines.push(fieldToZodLine(field, '  '));
  }
  
  // Update schema (all fields optional)
  const updateLines: string[] = [];
  for (const field of fields) {
    const optionalField = { ...field, isOptional: true };
    updateLines.push(fieldToZodLine(optionalField, '  '));
  }
  
  const rowSchema = `export const ${pascalName}RowSchema = z.object({\n${rowLines.join('\n')}\n});`;
  const insertSchema = `export const ${pascalName}InsertSchema = z.object({\n${insertLines.join('\n')}\n});`;
  const updateSchema = `export const ${pascalName}UpdateSchema = z.object({\n${updateLines.join('\n')}\n});`;
  
  return {
    rowSchema,
    insertSchema,
    updateSchema,
    enumImports,
    fieldCount: fields.length,
  };
}

// ============================================================================
// MAIN BUILDER FUNCTION
// ============================================================================

/**
 * Build validator schemas from a generated type file
 * 
 * @param tableName - Name of the table
 * @param deityFolder - Deity folder where type file is located
 * @returns ValidatorBuilderResult or null if parsing fails
 */
export function buildValidatorFromTypeFile(
  tableName: string,
  deityFolder: string
): ValidatorBuilderResult | null {
  const typeFilePath = path.join(
    PROJECT_ROOT,
    'src/types/generated',
    deityFolder,
    `${tableName}.ts`
  );
  
  if (!fs.existsSync(typeFilePath)) {
    console.warn(`Type file not found: ${typeFilePath}`);
    return null;
  }
  
  const fields = parseTypeFile(typeFilePath, tableName);
  
  if (!fields || fields.length === 0) {
    console.warn(`Could not parse fields from ${typeFilePath}`);
    return null;
  }
  
  return buildSchemas(fields, tableName);
}

/**
 * Generate the complete validator file content
 */
export function generateValidatorContent(
  tableName: string,
  deityFolder: string,
  handlingLevel: string
): string | null {
  const result = buildValidatorFromTypeFile(tableName, deityFolder);
  
  if (!result) {
    return null;
  }
  
  const pascalName = toPascalCase(tableName);
  const timestamp = new Date().toISOString();
  
  // Build imports
  let imports = `import { z } from 'zod';\n`;
  
  // Add enum imports (each from its own file)
  const uniqueEnumImports = [...new Set(result.enumImports)];
  for (const enumImport of uniqueEnumImports) {
    // Extract enum name from "ENUM_VALUES.userTier" -> "userTier"
    const enumName = enumImport.replace('ENUM_VALUES.', '');
    // Convert back to snake_case for import path
    const snakeName = enumName.replace(/([A-Z])/g, '_$1').toLowerCase().replace(/^_/, '');
    
    // Get deity folder for this enum
    const { getEnumFolder } = require('@/config/enum_mapping.js');
    const enumDeityFolder = getEnumFolder(snakeName);
    
    imports += `import { ENUM_VALUES } from '@/lib/constants/generated/${enumDeityFolder}/${snakeName}';\n`;
  }
  
  let content = `// =====================================================
// FILE: lib/validators/generated/${deityFolder}/${tableName}.ts
// HANDLING: ${handlingLevel}
// GENERATED: ${timestamp}
// BUILT FROM: types/generated/${deityFolder}/${tableName}.ts
// =====================================================

${imports}
// =====================================================
// ZOD SCHEMAS (Built from type definitions)
// =====================================================

${result.rowSchema}

${result.insertSchema}

${result.updateSchema}

// =====================================================
// TYPE INFERENCE
// =====================================================

export type ${pascalName}RowInput = z.infer<typeof ${pascalName}RowSchema>;
export type ${pascalName}InsertInput = z.infer<typeof ${pascalName}InsertSchema>;
export type ${pascalName}UpdateInput = z.infer<typeof ${pascalName}UpdateSchema>;

// =====================================================
// VALIDATION UTILITIES
// =====================================================

export function validate${pascalName}Row(data: unknown): data is ${pascalName}RowInput {
  try {
    ${pascalName}RowSchema.parse(data);
    return true;
  } catch {
    return false;
  }
}

export function validate${pascalName}Insert(data: unknown): data is ${pascalName}InsertInput {
  try {
    ${pascalName}InsertSchema.parse(data);
    return true;
  } catch {
    return false;
  }
}

export function validate${pascalName}Update(data: unknown): data is ${pascalName}UpdateInput {
  try {
    ${pascalName}UpdateSchema.parse(data);
    return true;
  } catch {
    return false;
  }
}

export function safeValidate${pascalName}Insert(data: unknown): {
  success: boolean;
  data?: ${pascalName}InsertInput;
  error?: z.ZodError;
} {
  const result = ${pascalName}InsertSchema.safeParse(data);
  if (result.success) {
    return { success: true, data: result.data };
  }
  return { success: false, error: result.error };
}
`;
  
  return content;
}