// src/scripts/shared/paths.ts
// ============================================================================
// CENTRALIZED PATH CONFIGURATION
// ============================================================================
// Single source of truth for all file paths used by GAIA and COSMIC
// All paths are absolute (resolved from project root)
// ============================================================================

import * as path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const PROJECT_ROOT = path.resolve(__dirname, '../../..');

// ============================================================================
// SOURCE FILES
// ============================================================================

/** Path to Supabase-generated database types */
export const DB_TYPES_PATH = path.join(PROJECT_ROOT, 'src/types/supabase/database.types.ts');
/** Path to generated database helpers */
export const HELPERS_PATH = path.join(PROJECT_ROOT, 'src/types/supabase/database.helpers.ts');
// Path to the generated enums helper
export const ENUMS_HELPER_PATH = path.join(PROJECT_ROOT, 'src/types/supabase/enums.ts');

// ============================================================================
// GENERATED OUTPUT PATHS (with /generated/ subfolder)
// ============================================================================

/** Base directory for generated constants */
export const CONSTANTS_BASE_PATH = path.join(PROJECT_ROOT, 'src/lib/constants/generated');

/** Base directory for generated validators */
export const VALIDATORS_BASE_PATH = path.join(PROJECT_ROOT, 'src/lib/validators/generated');

/** Base directory for generated types */
export const TYPES_BASE_PATH = path.join(PROJECT_ROOT, 'src/types/generated');

/** Base directory for generated utilities */
export const UTILS_BASE_PATH = path.join(PROJECT_ROOT, 'src/lib/utils/generated');

/** Base directory for generated hooks */
export const HOOKS_BASE_PATH = path.join(PROJECT_ROOT, 'src/hooks/generated');

/** Base directory for generated API routes */
export const API_BASE_PATH = path.join(PROJECT_ROOT, 'src/app/api/generated');

// ============================================================================
// COSMIC GENERATED OUTPUT PATHS
// ============================================================================

/** Base directory for cosmic generated styles */
export const COSMIC_STYLES_BASE_PATH = path.join(PROJECT_ROOT, 'src/styles/generated');

/** Path for generated Tailwind config */
export const TAILWIND_GENERATED_PATH = path.join(PROJECT_ROOT, 'tailwind.generated.config.mjs');

// ============================================================================
// CONFIGURATION FILES
// ============================================================================

/** Path to deity groups configuration */
export const DEITY_GROUPS_PATH = path.join(PROJECT_ROOT, 'src/config/deity_groups.ts');

/** Path to object categories configuration */
export const OBJECT_CATEGORIES_PATH = path.join(PROJECT_ROOT, 'src/config/object_categories.ts');

/** Path to enum mapping configuration */
export const ENUM_MAPPING_PATH = path.join(PROJECT_ROOT, 'src/config/enum_mapping.ts');

// ============================================================================
// REGISTRY AND TRACKING FILES
// ============================================================================

/** Path to system registry (autogenerated) */
export const SYSTEM_REGISTRY_PATH = path.join(PROJECT_ROOT, 'src/config/generated/system_registry.json');

/** Path to dependency map (autogenerated) */
export const DEPENDENCY_MAP_PATH = path.join(PROJECT_ROOT, 'src/config/generated/dependency_map.json');

/** Path to efficiency records (autogenerated) */
export const EFFICIENCY_RECORDS_PATH = path.join(PROJECT_ROOT, 'src/config/generated/efficiency_records.json');

// ============================================================================
// HELPER FUNCTIONS
// ============================================================================

/**
 * Get the deity-specific path for a generated file
 * @param basePath - Base path (e.g., TYPES_BASE_PATH)
 * @param deityFolder - Deity folder name (e.g., 'hestia_core')
 * @param fileName - File name (e.g., 'profiles.ts')
 * @returns Full absolute path
 */
export function getDeityFilePath(basePath: string, deityFolder: string, fileName: string): string {
  return path.join(basePath, deityFolder, fileName);
}

/**
 * Get the flat path for a generated file (no deity nesting)
 * @param basePath - Base path (e.g., API_BASE_PATH)
 * @param fileName - File name or route name (e.g., 'profiles')
 * @returns Full absolute path
 */
export function getFlatFilePath(basePath: string, fileName: string): string {
  return path.join(basePath, fileName);
}

/**
 * Get the relative path from project root
 * @param absolutePath - Absolute path to convert
 * @returns Relative path from project root
 */
export function toRelativePath(absolutePath: string): string {
  return path.relative(PROJECT_ROOT, absolutePath);
}

/**
 * Get the project root path
 */
export function getProjectRoot(): string {
  return PROJECT_ROOT;
}

// ============================================================================
// TYPE EXPORTS
// ============================================================================

export type { PROJECT_ROOT as ProjectRootType };